version: '3.8'

services:

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: geogramint_custom
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  mongo_data: